version: "3"
services:
  nginx:
    image: "hpehl/model-graph-nginx"
    ports:
      - "8080:8080"
  wf-latest:
    image: "hpehl/model-graph-wildfly"
    ports:
      - "7474:7474"
      - "7687:7687"
